// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// rcpparma_hcp
Rcpp::List rcpparma_hcp(NumericMatrix Fr, NumericMatrix Yr, int k, int lambda1, int lambda2, int lambda3, int iter);
RcppExport SEXP Rhcpp_rcpparma_hcp(SEXP FrSEXP, SEXP YrSEXP, SEXP kSEXP, SEXP lambda1SEXP, SEXP lambda2SEXP, SEXP lambda3SEXP, SEXP iterSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type Fr(FrSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Yr(YrSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type lambda1(lambda1SEXP);
    Rcpp::traits::input_parameter< int >::type lambda2(lambda2SEXP);
    Rcpp::traits::input_parameter< int >::type lambda3(lambda3SEXP);
    Rcpp::traits::input_parameter< int >::type iter(iterSEXP);
    __result = Rcpp::wrap(rcpparma_hcp(Fr, Yr, k, lambda1, lambda2, lambda3, iter));
    return __result;
END_RCPP
}
