# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393
rcpparma_hcp <- function(F, Y, k, lambda1, lambda2, lambda3, iter) {
    .Call('Rhcpp_rcpparma_hcp', PACKAGE = 'Rhcpp', F, Y, k, lambda1, lambda2, lambda3, iter)
}

