# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

##' Rcpp implementation of the HCP algorithm
##'
##' objective:
##' this function solves the following problem:
##' argmin_{Z,B,U}   ||Y-Z*B||_2 + lambda1*||Z-F*U||_2 + lambda2*||B||_2 +
##' lambda_3||U||_2
##'
##' to use the residual data: Residual = Y - Z*B
##' 
##' note: k>0, lambda1>0, lambda2>0, lambda3>0 must be set by the user based on
##' the data at hand. one can set these values using cross-validation, by
##' evaluating the "performance" of the  resulting residual data on a desired
##' task. typically, if lambda>5, then hidden factors match the known covariates closely.
##' @title Rcpp implementation of the HCP algorithm
##' @param F a matrix nxd of known covariates, where n is the number of
##' subjects and d is the number of known covariates. *must be standardize
##' (columns have 0 mean and constant SS).
##' @param Y a matrix of nxg of expression data (must be standardized (columns
##' scaled to have constant SS and mean 0). ** use standardize function to standardize F and Y. 
##' @param k  number of inferred hidden components (k is an integer)
##' @param lambda1 model parameter 1
##' @param lambda2 model parameter 1
##' @param lambda3 model parameter 1
##' @param iter (optional) iter: number of iterations (default = 100);
##' @return list
##' Z: matrix of hidden components, dimensionality: nxk
##' B: matrix of effects of hidden components, dimensionality: kxg
##' o: value of objective function on consecutive iterations.
##' @author mvaniterson
##' @references \url{http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0068141}
##' @examples
##' data(hcp)
##' F <- data$F
##' Y <- data$Y
##' k <- 10
##' lambda1 <- 20
##' lambda2 <- 1
##' lambda3 <- 1
##' iter <- 100
##' Rcpparmares <- rcpparma_hcp(Y, F, k, lambda1, lambda2, lambda3, iter)
rcpparma_hcp <- function(F, Y, k, lambda1, lambda2, lambda3, iter) {
    .Call('Rhcpp_rcpparma_hcp', PACKAGE = 'Rhcpp', F, Y, k, lambda1, lambda2, lambda3, iter)
}

